# Generated by Django 3.1 on 2020-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_assembly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicmodel',
            name='construct_csv',
            field=models.FileField(upload_to='./basic_files/input/constructs'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='parts_linkers_csv',
            field=models.FileField(upload_to='./basic_files/input/parts_linkers'),
        ),
    ]
